spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr_manage
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  main:
    banner-mode: off

